//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VkIM.rc
//
#define IDD_VKIM_DIALOG                 102
#define IDD_BROWSERDLG                  103
#define IDD_TALKDLG                     104
#define IDD_TALKTAB                     105
#define IDD_SETTINGSDLG                 106
#define IDD_SETTINGSNOTIFYDLG           107
#define IDD_LOADINGDLG                  108
#define IDD_NOTIFICATIONDLG             109
#define IDD_SETTINGSCONNDLG             110
#define IDD_SETTINGSCOMMONDLG           111
#define IDD_CAPTCHADLG                  112
#define IDD_MESSAGEBOARD                113
#define IDD_ABOUTDLG                    114
#define IDD_OPENTALKDLG                 115
#define IDD_SETFLISTSDLG                116
#define IDD_EPICFAIL                    117
#define IDD_STATUS                      118
#define IDR_MAINFRAME                   128
#define IDB_TREE_CLOSED                 133
#define IDB_TREE_OPENED                 134
#define IDI_TRAY_C                      141
#define IDI_TRAY_D                      142
#define IDI_PLAY                        145
#define IDB_WBUTTONS                    146
#define IDI_CHAT                        148
#define IDB_ABOUT_HEADER                149
#define IDI_ICON1                       151
#define IDI_BROWSE                      151
#define IDB_ATT_AUDIO                   152
#define IDB_ATT_PHOTO                   153
#define IDB_BITMAP3                     154
#define IDB_ATT_VIDEO                   154
#define IDC_EXPLORER1                   1002
#define IDC_TREE1                       1006
#define IDC_TAB1                        1007
#define IDC_MSG_FIELD                   1008
#define IDC_RICHEDIT21                  1009
#define IDC_USER_NAME                   1013
#define IDC_USER_STATUS                 1014
#define IDC_EDIT2                       1015
#define IDC_CL_SEARCH                   1015
#define IDC_EDIT8                       1016
#define IDC_AVA                         1017
#define IDC_SEND_BTN                    1018
#define IDC_BUTTON1                     1020
#define IDC_BUTTON2                     1021
#define IDC_LIST1                       1022
#define IDC_BUTTON3                     1022
#define IDC_BUTTON4                     1023
#define IDC_BUTTON7                     1024
#define IDC_BUTTON8                     1025
#define IDC_BUTTON9                     1026
#define IDC_BUTTON10                    1027
#define IDC_BUTTON5                     1028
#define IDC_BUTTON6                     1029
#define IDC_LOADING_TXT                 1049
#define IDC_USER_STATUS_S               1050
#define IDC_CHECK2                      1052
#define IDC_CHECK3                      1053
#define IDC_CHECK4                      1054
#define IDC_CHECK5                      1055
#define IDC_EDIT1                       1056
#define IDC_EDIT3                       1057
#define IDC_EDIT6                       1058
#define IDC_CLR_ALL                     1058
#define IDC_EDIT7                       1059
#define IDC_SEL_ALL                     1059
#define IDC_CHECK6                      1060
#define IDC_EDIT9                       1060
#define IDC_CHECK7                      1061
#define IDC_EDIT4                       1062
#define IDC_HL_TBB                      1063
#define IDC_CHECK9                      1064
#define IDC_CHECK10                     1065
#define IDC_EDIT5                       1066
#define IDC_TREE2                       1067
#define IDC_CHECK11                     1068
#define IDC_CHECK13                     1069
#define IDC_COMBO1                      1070
#define IDC_COMBO2                      1071
#define IDC_STATUS_CHANGE               1071
#define IDC_ST_ONLINE                   1072
#define IDC_ST_OFFLINE                  1073
#define IDC_NEW_MSGS                    1074
#define IDC_NTF_GROUPS                  1075
#define IDC_CHECK1                      1076
#define IDC_EDIT10                      1076
#define IDC_PROXY_LABEL                 1077
#define IDC_CHECK8                      1077
#define IDC_VKAPI_LABEL                 1078
#define IDC_CHECK12                     1078
#define IDC_PADDR_LABEL                 1080
#define IDC_PUNAME_LABEL                1081
#define IDC_PPASS_LABEL                 1082
#define IDC_PPORT_LABEL                 1083
#define IDC_API_ADDR                    1084
#define IDC_API_PORT                    1085
#define IDC_API_REQ                     1086
#define IDC_SKIN_LABEL                  1087
#define IDC_LANG_LABEL                  1088
#define IDC_EVENTS                      1090
#define IDC_UPD_I                       1091
#define IDC_UPD_S                       1092
#define IDC_SPIN1                       1093
#define IDC_LH2                         1094
#define IDC_IMG                         1095
#define IDC_TITLE                       1096
#define IDC_RADIO1                      1097
#define IDC_RADIO2                      1098
#define IDC_SK                          1099
#define IDC_RADIO3                      1099
#define IDC_SYSLINK1                    1100
#define IDC_NT                          1101
#define IDC_STATIC1                     1102
#define IDC_SYSLINK2                    1103
#define IDC_ICON                        1105
#define IDC_STATIC_TXT                  1106
#define IDC_ST                          1107

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        155
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1109
#define _APS_NEXT_SYMED_VALUE           120
#endif
#endif
